### ISSUE TITLE
插件 Epic 报错

### ISSUE THREAD

**Issue by AnotiaWang** [Xtao-Labs/PagerMaid_Plugins#202]
### BUG 发生地址
插件 `EPIC`

### 预期是什么？
显示喜加一信息

### 实际发生了什么？
报错

### 额外信息（日志、报错等）
```
获取 Epic 信息错误：<class 'AttributeError'>
type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by AnotiaWang** [comment]
虽然没有使用模板，但我已经提供了复现问题的充分描述，或者我的问题无法使用模板表达。

**Comment by evanjh** [comment]
@AnotiaWang

**Comment by xtaodada** [comment]
`fromisoformat` 是 python 3.7 新增加的内容，请升级 python 版本到 3.7+

**Comment by AnotiaWang** [comment]
> `fromisoformat` 是 python 3.7 新增加的内容，请升级 python 版本到 3.7+

好的，谢谢解答

**Comment by evanjh** [comment]
@AnotiaWang 炸群啦~
