### ISSUE TITLE
sendat 对固定时间的解析存在问题

### ISSUE THREAD

**Issue by OwO996** [Xtao-Labs/PagerMaid_Plugins#87]
![image](https://user-images.githubusercontent.com/48612045/101929408-c27cc700-3c11-11eb-9c4a-0c279ea50241.png)
这个样子的。设置了消息，但是到点没有自动发送此消息。

**Comment by a-fruity-melon** [comment]
@OwO996 您好，已知悉此问题，将尽快修复。
